//! SpanDSP FFI bindings.
//!
//! This module provides Rust bindings to the SpanDSP C library.
//! Bindings are automatically generated by bindgen during the build process.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(improper_ctypes)]
#![allow(clippy::all)]

// Include the generated bindings from build.rs when spandsp-native feature is enabled
#[cfg(feature = "spandsp-native")]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/spandsp_bindings.rs"));
}

#[cfg(feature = "spandsp-native")]
pub use generated::*;

// ========================================
// Native UDPTL bindings (from vendor/spandsp/tests/udptl.c)
// These are NOT part of the SpanDSP shared library — they come from
// the separately compiled udptl.c (Steve Underwood's reference implementation).
// ========================================
#[cfg(feature = "spandsp-native")]
mod native_udptl {
    use std::os::raw::{c_int, c_void};

    /// Opaque UDPTL state (matches struct udptl_state_s from udptl.h)
    #[repr(C)]
    pub struct udptl_state_t {
        _private: [u8; 0],
    }

    /// UDPTL RX callback: called for each decoded IFP packet
    pub type udptl_rx_packet_handler_t = Option<
        unsafe extern "C" fn(
            user_data: *mut c_void,
            msg: *const u8,
            len: c_int,
            seq_no: c_int,
        ) -> c_int,
    >;

    /// UDPTL error correction modes
    pub const UDPTL_ERROR_CORRECTION_NONE: c_int = 0;
    pub const UDPTL_ERROR_CORRECTION_FEC: c_int = 1;
    pub const UDPTL_ERROR_CORRECTION_REDUNDANCY: c_int = 2;

    extern "C" {
        /// Initialize a UDPTL context.
        pub fn udptl_init(
            s: *mut udptl_state_t,
            ec_scheme: c_int,
            span: c_int,
            entries: c_int,
            rx_packet_handler: udptl_rx_packet_handler_t,
            user_data: *mut c_void,
        ) -> *mut udptl_state_t;

        /// Process a received UDPTL packet (decodes and delivers IFP via callback).
        pub fn udptl_rx_packet(
            s: *mut udptl_state_t,
            buf: *const u8,
            len: c_int,
        ) -> c_int;

        /// Build a UDPTL packet from an IFP payload.
        /// Returns the total packet length, or -1 on error.
        pub fn udptl_build_packet(
            s: *mut udptl_state_t,
            buf: *mut u8,
            msg: *const u8,
            msg_len: c_int,
        ) -> c_int;

        /// Set error correction parameters.
        pub fn udptl_set_error_correction(
            s: *mut udptl_state_t,
            ec_scheme: c_int,
            span: c_int,
            entries: c_int,
        ) -> c_int;

        /// Set the maximum datagram size the far end accepts.
        pub fn udptl_set_far_max_datagram(
            s: *mut udptl_state_t,
            max_datagram: c_int,
        ) -> c_int;

        /// Set the maximum datagram size we accept.
        pub fn udptl_set_local_max_datagram(
            s: *mut udptl_state_t,
            max_datagram: c_int,
        ) -> c_int;

        /// Free a UDPTL context.
        pub fn udptl_free(s: *mut udptl_state_t) -> c_int;

        /// Release a UDPTL context (does not free memory).
        pub fn udptl_release(s: *mut udptl_state_t) -> c_int;
    }
}

#[cfg(feature = "spandsp-native")]
pub use native_udptl::*;

// Fallback definitions when native SpanDSP is not available
#[cfg(not(feature = "spandsp-native"))]
mod fallback {
    use std::os::raw::{c_int, c_char, c_void};

    /// Opaque T.30 fax protocol state
    #[repr(C)]
    pub struct t30_state_t {
        _private: [u8; 0],
    }

    /// Opaque T.30 statistics
    #[repr(C)]
    #[derive(Debug, Default, Clone)]
    pub struct t30_stats_t {
        pub bit_rate: c_int,
        pub error_correcting_mode: c_int,
        pub pages_tx: c_int,
        pub pages_rx: c_int,
        pub pages_in_file: c_int,
        pub width: c_int,
        pub length: c_int,
        pub bad_rows: c_int,
        pub longest_bad_row_run: c_int,
        pub x_resolution: c_int,
        pub y_resolution: c_int,
        pub encoding: c_int,
        pub image_size: c_int,
        pub current_status: c_int,
    }

    /// Opaque T.38 core state
    #[repr(C)]
    pub struct t38_core_state_t {
        _private: [u8; 0],
    }

    /// Opaque T.38 terminal state
    #[repr(C)]
    pub struct t38_terminal_state_t {
        _private: [u8; 0],
    }

    /// Opaque high-level fax state
    #[repr(C)]
    pub struct fax_state_t {
        _private: [u8; 0],
    }

    /// Logging state
    #[repr(C)]
    pub struct logging_state_t {
        _private: [u8; 0],
    }

    /// T.30 phase handler callback types
    pub type t30_phase_b_handler_t = Option<unsafe extern "C" fn(
        s: *mut t30_state_t,
        user_data: *mut c_void,
        result: c_int,
    ) -> c_int>;
    
    pub type t30_phase_d_handler_t = Option<unsafe extern "C" fn(
        s: *mut t30_state_t,
        user_data: *mut c_void,
        result: c_int,
    ) -> c_int>;
    
    pub type t30_phase_e_handler_t = Option<unsafe extern "C" fn(
        s: *mut t30_state_t,
        user_data: *mut c_void,
        completion_code: c_int,
    )>;

    pub type t30_real_time_frame_handler_t = Option<unsafe extern "C" fn(
        s: *mut t30_state_t,
        user_data: *mut c_void,
        direction: c_int,
        msg: *const u8,
        len: c_int,
    )>;

    /// T.38 TX packet handler callback type
    pub type t38_tx_packet_handler_t = Option<unsafe extern "C" fn(
        s: *mut t38_core_state_t,
        user_data: *mut c_void,
        buf: *const u8,
        len: c_int,
        count: c_int,
    ) -> c_int>;

    /// T.30 error codes
    pub const T30_ERR_OK: c_int = 0;
    pub const T30_ERR_CEDTONE: c_int = 1;
    pub const T30_ERR_T0_EXPIRED: c_int = 2;
    pub const T30_ERR_T1_EXPIRED: c_int = 3;
    pub const T30_ERR_T3_EXPIRED: c_int = 4;

    // ========================================
    // Fax state functions (G.711 audio mode)
    // ========================================
    
    pub unsafe fn fax_init(_s: *mut fax_state_t, _calling_party: c_int) -> *mut fax_state_t {
        std::ptr::null_mut()
    }
    
    pub unsafe fn fax_free(_s: *mut fax_state_t) -> c_int { 0 }
    pub unsafe fn fax_release(_s: *mut fax_state_t) -> c_int { 0 }
    pub unsafe fn fax_restart(_s: *mut fax_state_t, _calling_party: c_int) -> *mut fax_state_t { std::ptr::null_mut() }
    pub unsafe fn fax_tx(_s: *mut fax_state_t, _amp: *mut i16, _max_len: c_int) -> c_int { 0 }
    pub unsafe fn fax_rx(_s: *mut fax_state_t, _amp: *const i16, _len: c_int) -> c_int { 0 }
    pub unsafe fn fax_rx_fillin(_s: *mut fax_state_t, _len: c_int) -> c_int { 0 }
    pub unsafe fn fax_get_t30_state(_s: *mut fax_state_t) -> *mut t30_state_t { std::ptr::null_mut() }
    pub unsafe fn fax_get_logging_state(_s: *mut fax_state_t) -> *mut logging_state_t { std::ptr::null_mut() }
    pub unsafe fn fax_set_transmit_on_idle(_s: *mut fax_state_t, _val: c_int) {}
    
    // ========================================
    // T.30 protocol functions
    // ========================================
    
    pub unsafe fn t30_set_tx_file(_s: *mut t30_state_t, _file: *const c_char, _start: c_int, _stop: c_int) -> c_int {
        tracing::info!("t30_set_tx_file called without native SpanDSP");
        -1
    }
    pub unsafe fn t30_set_rx_file(_s: *mut t30_state_t, _file: *const c_char, _start: c_int) -> c_int {
        tracing::info!("t30_set_rx_file called without native SpanDSP");
        -1
    }
    pub unsafe fn t30_set_tx_ident(_s: *mut t30_state_t, _id: *const c_char) -> c_int {
        tracing::info!("t30_set_tx_ident called without native SpanDSP");
        -1
    }
    pub unsafe fn t30_set_supported_modems(_s: *mut t30_state_t, _modem_types: c_int) -> c_int {
        tracing::info!("t30_set_supported_modems called without native SpanDSP");
        -1
    }
    pub unsafe fn t30_set_ecm_capability(_s: *mut t30_state_t, _enabled: c_int) -> c_int {
        tracing::info!("t30_set_ecm_capability called without native SpanDSP");
        -1
    }
    pub unsafe fn t30_set_supported_resolutions(_s: *mut t30_state_t, _supported_resolutions: c_int) -> c_int {
        tracing::info!("t30_set_supported_resolutions called without native SpanDSP");
        -1
    }
    pub unsafe fn t30_set_phase_b_handler(_s: *mut t30_state_t, _handler: t30_phase_b_handler_t, _user: *mut c_void) {}
    pub unsafe fn t30_set_phase_d_handler(_s: *mut t30_state_t, _handler: t30_phase_d_handler_t, _user: *mut c_void) {}
    pub unsafe fn t30_set_phase_e_handler(_s: *mut t30_state_t, _handler: t30_phase_e_handler_t, _user: *mut c_void) {}
    pub unsafe fn t30_set_real_time_frame_handler(_s: *mut t30_state_t, _handler: t30_real_time_frame_handler_t, _user: *mut c_void) {}
    pub unsafe fn t30_get_transfer_statistics(_s: *mut t30_state_t, _stats: *mut t30_stats_t) {}
    pub unsafe fn t30_get_rx_ident(_s: *mut t30_state_t) -> *const c_char { std::ptr::null() }
    pub unsafe fn t30_terminate(_s: *mut t30_state_t) {}
    pub unsafe fn t30_timer_update(_s: *mut t30_state_t, _samples: c_int) {}
    
    // ========================================
    // T.38 core functions
    // ========================================
    
    pub unsafe fn t38_core_init(_s: *mut t38_core_state_t, _handler: *mut c_void, _user: *mut c_void) -> *mut t38_core_state_t { std::ptr::null_mut() }
    pub unsafe fn t38_core_free(_s: *mut t38_core_state_t) -> c_int { 0 }
    pub unsafe fn t38_core_rx_ifp_packet(_s: *mut t38_core_state_t, _buf: *const u8, _len: c_int, _seq: u16) -> c_int { 0 }
    pub unsafe fn t38_core_send_indicator(_s: *mut t38_core_state_t, _indicator: c_int) -> c_int { 0 }
    pub unsafe fn t38_core_send_data(_s: *mut t38_core_state_t, _type: c_int, _field: c_int, _data: *const u8, _len: c_int, _count: c_int) -> c_int { 0 }
    pub unsafe fn t38_set_t38_version(_s: *mut t38_core_state_t, _version: c_int) -> c_int { 0 }
    pub unsafe fn t38_set_redundancy_control(_s: *mut t38_core_state_t, _category: c_int, _setting: c_int) -> c_int { 0 }
    pub unsafe fn t38_set_data_rate_management_method(_s: *mut t38_core_state_t, _method: c_int) -> c_int { 0 }
    pub unsafe fn t38_set_data_transport_protocol(_s: *mut t38_core_state_t, _protocol: c_int) -> c_int { 0 }
    pub unsafe fn t38_set_max_datagram_size(_s: *mut t38_core_state_t, _max_size: c_int) -> c_int { 0 }
    pub unsafe fn t38_set_tep_handling(_s: *mut t38_core_state_t, _use_tep: c_int) -> c_int { 0 }
    
    // ========================================
    // T.38 terminal functions (T.38 endpoint)
    // ========================================
    
    pub unsafe fn t38_terminal_init(
        _s: *mut t38_terminal_state_t,
        _calling_party: c_int,
        _tx_packet_handler: t38_tx_packet_handler_t,
        _tx_packet_user_data: *mut c_void,
    ) -> *mut t38_terminal_state_t {
        tracing::info!("t38_terminal_init called without native SpanDSP");
        std::ptr::null_mut()
    }
    
    pub unsafe fn t38_terminal_free(_s: *mut t38_terminal_state_t) -> c_int { 0 }
    pub unsafe fn t38_terminal_release(_s: *mut t38_terminal_state_t) -> c_int { 0 }
    pub unsafe fn t38_terminal_get_t30_state(_s: *mut t38_terminal_state_t) -> *mut t30_state_t { std::ptr::null_mut() }
    pub unsafe fn t38_terminal_get_t38_core_state(_s: *mut t38_terminal_state_t) -> *mut t38_core_state_t { std::ptr::null_mut() }
    pub unsafe fn t38_terminal_get_logging_state(_s: *mut t38_terminal_state_t) -> *mut logging_state_t { std::ptr::null_mut() }
    pub unsafe fn t38_terminal_send_timeout(_s: *mut t38_terminal_state_t, _samples: c_int) -> c_int { 0 }
    pub unsafe fn t38_terminal_restart(_s: *mut t38_terminal_state_t, _calling_party: c_int) -> c_int {
        tracing::info!("t38_terminal_restart called without native SpanDSP");
        -1
    }
    pub unsafe fn t38_terminal_set_tep_mode(_s: *mut t38_terminal_state_t, _use_tep: c_int) {}
    pub unsafe fn t38_terminal_set_fill_bit_removal(_s: *mut t38_terminal_state_t, _remove: c_int) {}
    
    // ========================================
    // Logging functions
    // ========================================
    
    pub unsafe fn span_log_init(_s: *mut logging_state_t, _level: c_int, _tag: *const c_char) -> *mut logging_state_t { std::ptr::null_mut() }
    pub unsafe fn span_log_set_level(_s: *mut logging_state_t, _level: c_int) -> c_int { 0 }
    pub unsafe fn span_log_set_tag(_s: *mut logging_state_t, _tag: *const c_char) -> c_int { 0 }
    
    // ========================================
    // UDPTL stub functions
    // ========================================
    
    /// Opaque UDPTL state
    #[repr(C)]
    pub struct udptl_state_t {
        _private: [u8; 0],
    }
    
    pub type udptl_rx_packet_handler_t = Option<
        unsafe extern "C" fn(
            user_data: *mut c_void,
            msg: *const u8,
            len: c_int,
            seq_no: c_int,
        ) -> c_int,
    >;
    
    pub const UDPTL_ERROR_CORRECTION_NONE: c_int = 0;
    pub const UDPTL_ERROR_CORRECTION_FEC: c_int = 1;
    pub const UDPTL_ERROR_CORRECTION_REDUNDANCY: c_int = 2;
    
    pub unsafe fn udptl_init(_s: *mut udptl_state_t, _ec: c_int, _span: c_int, _entries: c_int, _handler: udptl_rx_packet_handler_t, _user: *mut c_void) -> *mut udptl_state_t { std::ptr::null_mut() }
    pub unsafe fn udptl_rx_packet(_s: *mut udptl_state_t, _buf: *const u8, _len: c_int) -> c_int { -1 }
    pub unsafe fn udptl_build_packet(_s: *mut udptl_state_t, _buf: *mut u8, _msg: *const u8, _msg_len: c_int) -> c_int { -1 }
    pub unsafe fn udptl_set_error_correction(_s: *mut udptl_state_t, _ec: c_int, _span: c_int, _entries: c_int) -> c_int { -1 }
    pub unsafe fn udptl_set_far_max_datagram(_s: *mut udptl_state_t, _max: c_int) -> c_int { -1 }
    pub unsafe fn udptl_set_local_max_datagram(_s: *mut udptl_state_t, _max: c_int) -> c_int { -1 }
    pub unsafe fn udptl_free(_s: *mut udptl_state_t) -> c_int { 0 }
    pub unsafe fn udptl_release(_s: *mut udptl_state_t) -> c_int { 0 }
}

#[cfg(not(feature = "spandsp-native"))]
pub use fallback::*;

/// Sample rate for fax audio (8kHz)
pub const FAX_SAMPLE_RATE: u32 = 8000;

/// Samples per 20ms frame (standard RTP packet)
pub const FAX_SAMPLES_PER_FRAME: usize = 160;

/// Check if SpanDSP native support is available
pub const fn is_spandsp_available() -> bool {
    cfg!(feature = "spandsp-native")
}

/// Modem type constants per ITU-T T.30
pub mod modems {
    /// V.27ter - 2400/4800 bps (mandatory for Group 3)
    pub const T30_SUPPORT_V27TER: i32 = 0x01;
    /// V.29 - 7200/9600 bps
    pub const T30_SUPPORT_V29: i32 = 0x02;
    /// V.17 - 7200-14400 bps
    pub const T30_SUPPORT_V17: i32 = 0x04;
    /// V.34 - 2400-33600 bps (Super G3)
    pub const T30_SUPPORT_V34: i32 = 0x08;
    
    /// Standard fax modems (V.27ter + V.29 + V.17)
    pub const T30_SUPPORT_STANDARD: i32 = T30_SUPPORT_V27TER | T30_SUPPORT_V29 | T30_SUPPORT_V17;
    
    /// All modems including Super G3
    pub const T30_SUPPORT_ALL: i32 = T30_SUPPORT_STANDARD | T30_SUPPORT_V34;
}

/// T.4 bilevel image resolution flags (from spandsp/t4_rx.h)
/// Used with t30_set_supported_bilevel_resolutions()
pub mod resolutions {
    /// Standard FAX resolution 204dpi x 98dpi
    pub const T4_RESOLUTION_R8_STANDARD: i32 = 0x01;
    /// Fine FAX resolution 204dpi x 196dpi
    pub const T4_RESOLUTION_R8_FINE: i32 = 0x02;
    /// Super-fine FAX resolution 204dpi x 391dpi
    pub const T4_RESOLUTION_R8_SUPERFINE: i32 = 0x04;
    /// Double FAX resolution 408dpi x 391dpi
    pub const T4_RESOLUTION_R16_SUPERFINE: i32 = 0x08;
    /// 200dpi x 100dpi
    pub const T4_RESOLUTION_200_100: i32 = 0x20;
    /// 200dpi x 200dpi
    pub const T4_RESOLUTION_200_200: i32 = 0x40;
    /// 200dpi x 400dpi
    pub const T4_RESOLUTION_200_400: i32 = 0x80;
    /// 300dpi x 300dpi
    pub const T4_RESOLUTION_300_300: i32 = 0x100;
    /// 400dpi x 400dpi
    pub const T4_RESOLUTION_400_400: i32 = 0x400;
    /// 600dpi x 600dpi
    pub const T4_RESOLUTION_600_600: i32 = 0x1000;
    /// 1200dpi x 1200dpi
    pub const T4_RESOLUTION_1200_1200: i32 = 0x4000;

    /// Standard support: R8 standard + fine (most common fax resolutions)
    pub const T4_RESOLUTION_FAX_STANDARD: i32 = T4_RESOLUTION_R8_STANDARD | T4_RESOLUTION_R8_FINE;
    /// Extended support: also includes 200x200 and 300x300
    pub const T4_RESOLUTION_FAX_EXTENDED: i32 = T4_RESOLUTION_FAX_STANDARD
        | T4_RESOLUTION_R8_SUPERFINE
        | T4_RESOLUTION_200_200
        | T4_RESOLUTION_300_300;
}

/// T.30 error codes per SpanDSP/ITU-T T.30
pub mod t30_errors {
    /// Success - no error
    pub const T30_ERR_OK: i32 = 0;
    /// CED tone received but no DIS/DTC
    pub const T30_ERR_CEDTONE: i32 = 1;
    /// T0 timer expired (no initial response)
    pub const T30_ERR_T0_EXPIRED: i32 = 2;
    /// T1 timer expired (no response to DIS/DTC)
    pub const T30_ERR_T1_EXPIRED: i32 = 3;
    /// T3 timer expired (no response to commands)
    pub const T30_ERR_T3_EXPIRED: i32 = 4;
    /// HDLC carrier lost
    pub const T30_ERR_HDLC_CARRIER: i32 = 5;
    /// Cannot train (modem incompatibility or noise)
    pub const T30_ERR_CANNOT_TRAIN: i32 = 6;
    /// Operator intervention failed
    pub const T30_ERR_OPER_INT_FAIL: i32 = 7;
    /// Incompatible destination
    pub const T30_ERR_INCOMPATIBLE: i32 = 8;
    /// RX incapable
    pub const T30_ERR_RX_INCAPABLE: i32 = 9;
    /// TX incapable
    pub const T30_ERR_TX_INCAPABLE: i32 = 10;
    /// No resolution support
    pub const T30_ERR_NORESSUPPORT: i32 = 11;
    /// No size support
    pub const T30_ERR_NOSIZESUPPORT: i32 = 12;
    /// Unexpected message received
    pub const T30_ERR_UNEXPECTED: i32 = 13;
    /// Bad DCS received during TX
    pub const T30_ERR_TX_BADDCS: i32 = 14;
    /// Bad page received during TX
    pub const T30_ERR_TX_BADPG: i32 = 15;
    /// ECM phase D error during TX
    pub const T30_ERR_TX_ECMPHD: i32 = 16;
    /// Got DCN during TX
    pub const T30_ERR_TX_GOTDCN: i32 = 17;
    /// Invalid response during TX
    pub const T30_ERR_TX_INVALRSP: i32 = 18;
    /// No DIS received during TX
    pub const T30_ERR_TX_NODIS: i32 = 19;
    /// Phase B dead during TX
    pub const T30_ERR_TX_PHBDEAD: i32 = 20;
    /// Phase D dead during TX
    pub const T30_ERR_TX_PHDDEAD: i32 = 21;
    /// T5 timer expired during TX
    pub const T30_ERR_TX_T5EXP: i32 = 22;
    /// ECM phase D error during RX
    pub const T30_ERR_RX_ECMPHD: i32 = 23;
    /// Got DCS during RX
    pub const T30_ERR_RX_GOTDCS: i32 = 24;
    /// Invalid command during RX
    pub const T30_ERR_RX_INVALCMD: i32 = 25;
    /// No carrier during RX
    pub const T30_ERR_RX_NOCARRIER: i32 = 26;
    /// No EOL during RX
    pub const T30_ERR_RX_NOEOL: i32 = 27;
    /// No fax detected during RX
    pub const T30_ERR_RX_NOFAX: i32 = 28;
    /// T2 expired with DCN during RX
    pub const T30_ERR_RX_T2EXPDCN: i32 = 29;
    /// T2 expired with D during RX
    pub const T30_ERR_RX_T2EXPD: i32 = 30;
    /// T2 expired with fax during RX
    pub const T30_ERR_RX_T2EXPFAX: i32 = 31;
    /// T2 expired with MPS during RX
    pub const T30_ERR_RX_T2EXPMPS: i32 = 32;
    /// T2 expired with RR during RX
    pub const T30_ERR_RX_T2EXPRR: i32 = 33;
    /// T2 expired during RX
    pub const T30_ERR_RX_T2EXP: i32 = 34;
    /// Received DCN unexpectedly
    pub const T30_ERR_RX_DCNWHY: i32 = 35;
    /// DCN with data during RX
    pub const T30_ERR_RX_DCNDATA: i32 = 36;
    /// DCN with fax during RX
    pub const T30_ERR_RX_DCNFAX: i32 = 37;
    /// DCN with phase D during RX
    pub const T30_ERR_RX_DCNPHD: i32 = 38;
    /// DCN with RRD during RX
    pub const T30_ERR_RX_DCNRRD: i32 = 39;
    /// DCN no return during RX
    pub const T30_ERR_RX_DCNNORTN: i32 = 40;
    /// File error
    pub const T30_ERR_FILEERROR: i32 = 41;
    /// No page to send
    pub const T30_ERR_NOPAGE: i32 = 42;
    /// Bad TIFF file
    pub const T30_ERR_BADTIFF: i32 = 43;
    /// Bad page in TIFF
    pub const T30_ERR_BADPAGE: i32 = 44;
    /// Bad TIFF tag
    pub const T30_ERR_BADTAG: i32 = 45;
    /// Bad TIFF header
    pub const T30_ERR_BADTIFFHDR: i32 = 46;
    /// Out of memory
    pub const T30_ERR_NOMEM: i32 = 47;
}

/// T.38 protocol constants
pub mod t38 {
    /// T.38 indicator types
    pub const T38_IND_NO_SIGNAL: i32 = 0;
    pub const T38_IND_CNG: i32 = 1;
    pub const T38_IND_CED: i32 = 2;
    pub const T38_IND_V21_PREAMBLE: i32 = 3;
    pub const T38_IND_V27TER_2400_TRAINING: i32 = 4;
    pub const T38_IND_V27TER_4800_TRAINING: i32 = 5;
    pub const T38_IND_V29_7200_TRAINING: i32 = 6;
    pub const T38_IND_V29_9600_TRAINING: i32 = 7;
    pub const T38_IND_V17_7200_SHORT_TRAINING: i32 = 8;
    pub const T38_IND_V17_7200_LONG_TRAINING: i32 = 9;
    pub const T38_IND_V17_9600_SHORT_TRAINING: i32 = 10;
    pub const T38_IND_V17_9600_LONG_TRAINING: i32 = 11;
    pub const T38_IND_V17_12000_SHORT_TRAINING: i32 = 12;
    pub const T38_IND_V17_12000_LONG_TRAINING: i32 = 13;
    pub const T38_IND_V17_14400_SHORT_TRAINING: i32 = 14;
    pub const T38_IND_V17_14400_LONG_TRAINING: i32 = 15;
    
    /// T.38 data types
    pub const T38_DATA_V21: i32 = 0;
    pub const T38_DATA_V27TER_2400: i32 = 1;
    pub const T38_DATA_V27TER_4800: i32 = 2;
    pub const T38_DATA_V29_7200: i32 = 3;
    pub const T38_DATA_V29_9600: i32 = 4;
    pub const T38_DATA_V17_7200: i32 = 5;
    pub const T38_DATA_V17_9600: i32 = 6;
    pub const T38_DATA_V17_12000: i32 = 7;
    pub const T38_DATA_V17_14400: i32 = 8;
    
    /// T.38 field types
    pub const T38_FIELD_HDLC_DATA: i32 = 0;
    pub const T38_FIELD_HDLC_SIG_END: i32 = 1;
    pub const T38_FIELD_HDLC_FCS_OK: i32 = 2;
    pub const T38_FIELD_HDLC_FCS_BAD: i32 = 3;
    pub const T38_FIELD_HDLC_FCS_OK_SIG_END: i32 = 4;
    pub const T38_FIELD_HDLC_FCS_BAD_SIG_END: i32 = 5;
    pub const T38_FIELD_T4_NON_ECM_DATA: i32 = 6;
    pub const T38_FIELD_T4_NON_ECM_SIG_END: i32 = 7;
}
