//! SpanDSP-based fax implementation.
//!
//! This module provides T.38 and G.711 passthrough fax functionality using the industry-standard
//! SpanDSP library. SpanDSP is used by FreeSWITCH, Asterisk, and virtually every production
//! fax server worldwide, providing ~99.5% success rate.
//!
//! ## Industry Standards Implemented
//! - **ITU-T T.30**: Group 3 fax protocol (negotiation, page transfer, error handling)
//! - **ITU-T T.38**: Real-time virtual faxing with UDPTL transport
//! - **ITU-T V.17**: 14400/12000/9600/7200 bps modulation
//! - **ITU-T V.29**: 9600/7200 bps modulation
//! - **ITU-T V.27ter**: 4800/2400 bps modulation
//! - **ITU-T V.34**: 33600 bps modulation (Super G3)
//! - **G.711 µ-law (PCMU)** and **A-law (PCMA)** codec support
//!
//! ## Architecture
//! - `bindings` - Raw FFI bindings to SpanDSP C library (generated by bindgen)
//! - `session` - Safe Rust wrapper around SpanDSP fax session state (G.711 mode)
//! - `t38_session` - T.38 terminal session wrapper with UDPTL
//! - `udptl` - UDPTL transport for T.38 with redundancy-based error correction
//! - `fax` - Tauri commands for fax operations
//! - `fax_media` - RTP audio I/O for G.711 fax passthrough
//! - `tiff` - TIFF file handling utilities
//!
//! ## Usage
//! The primary entry point is via Tauri commands in the `fax` module.
//! For programmatic use:
//!
//! ```ignore
//! use spandsp::{FaxSession, FaxSendOptions, FaxMode};
//!
//! // Configure fax options
//! let options = FaxSendOptions {
//!     mode: FaxMode::T38Udptl,
//!     ecm: true,
//!     baud_rate: 14400,
//!     ..Default::default()
//! };
//!
//! // Create and run session
//! let mut session = FaxSession::new_send("document.tiff", &options)?;
//! session.start()?;
//! // ... handle audio/UDPTL I/O ...
//! let result = session.stop();
//! ```

pub mod bindings;
pub mod fax;
pub mod fax_media;
pub mod session;
pub mod t38_session;
pub mod tiff;
pub mod udptl;

// Core session types
#[allow(unused_imports)]
pub use session::{
    FaxMode, FaxResult, FaxSendOptions, FaxSession, G711Variant, ModemType, T30Error,
};

// T.38 session types
#[allow(unused_imports)]
pub use t38_session::{T38Config, T38Result, T38Session};

// UDPTL types (native SpanDSP implementation)
#[allow(unused_imports)]
pub use udptl::{NativeUdptl, UdptlEcMode};

// Tauri command handlers
#[allow(unused_imports)]
pub use fax::*;
