//! Agent configuration types.
//!
//! The `AgentConfig` is generated by the controller and bundled with the
//! agent binary. It contains everything the agent needs to connect back.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Configuration for a remote agent instance, generated by the controller.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentConfig {
    /// Unique agent identifier (UUID).
    pub agent_id: String,

    /// The controller's address to connect to (e.g., "192.168.1.100:9147").
    pub controller_address: String,

    /// Whether to use TLS for the WebSocket connection.
    #[serde(default = "default_true")]
    pub use_tls: bool,

    /// Pre-shared authentication token (hex-encoded).
    pub auth_token: String,

    /// Optional expiration timestamp. After this time, the agent will
    /// self-destruct (shut down and remove its binary from the target system).
    pub expires_at: Option<DateTime<Utc>>,

    /// Human-readable label for this agent config.
    pub label: Option<String>,

    /// The controller's display name (shown in the agent's tray tooltip).
    pub controller_name: Option<String>,
}

fn default_true() -> bool {
    true
}

impl AgentConfig {
    /// Check if this config has expired.
    pub fn is_expired(&self) -> bool {
        if let Some(expires_at) = self.expires_at {
            Utc::now() > expires_at
        } else {
            false
        }
    }

    /// Load from a JSON file path.
    pub fn load_from_file(path: &std::path::Path) -> Result<Self, String> {
        let contents =
            std::fs::read_to_string(path).map_err(|e| format!("Failed to read config: {e}"))?;
        serde_json::from_str(&contents).map_err(|e| format!("Failed to parse config: {e}"))
    }

    /// Save to a JSON file path.
    pub fn save_to_file(&self, path: &std::path::Path) -> Result<(), String> {
        let json = serde_json::to_string_pretty(self)
            .map_err(|e| format!("Failed to serialize config: {e}"))?;
        std::fs::write(path, json).map_err(|e| format!("Failed to write config: {e}"))
    }
}

/// Default listener port for the controller's WebSocket server.
pub const DEFAULT_LISTENER_PORT: u16 = 9147;
